<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HRManagementApp.Core\HRManagementApp.Core.csproj" />
    <ProjectReference Include="..\HRManagementApp.DataAccess\HRManagementApp.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
